version: "1.0"

services:
  mysql666:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    command:
      - "create database simple_oauth2;"
    environment:
      MYSQL_ROOT: "root"
      MYSQL_DATABASE: "simple_oauth2"
      MYSQL_PASSWORD: "zhaoxijun7"
  redis777:
    image: "redis:latest"
    ports:
      - "6379:6379"
  App:
    build: ./Dockerfile
    ports:
      - "8080:8080"